- howard/objects/variants.py
- howard/tools/calculation.py
- howard/tools/tools.py
- tests/test_objects_variants.py
- tests/test_tools_calculation.py
variant_id on position and variant type
Improve calculations (operations list, trio, validation_id...)
some fixes
> improve calculations #17, add variant_id #12, improve trio #18

- howard/tools/__init__.py
- howard/tools/from_annovar.py
- howard/tools/tools.py
Add Annovar to VCF/Parquet conversion
> Annovar to VCF/Parquet #20

- Dockerfile
- howard/objects/variants.py
Due to new release of duckdb that include bgzip de/compression, read_csv_auto is able to directly load data into a table.
> refactor load data with read_csv_auto

- howard/tools/from_annovar.py
- howard/tools/tools.py
- misc/functions.py
- tests/test_tools_from_annovar.py
Improve using parquet format and duckdb. Useful for large files.
Some fixes too
> improve perf using parquet #29

- howard/tools/from_annovar.py
- tests/test_tools_from_annovar.py
improve from_annovar with duckdb and parquet
> improve from_annovar tool #29

- howard/commons.py
- howard/main.py
- howard/objects/variants.py
- howard/tools/from_annovar.py
- howard/tools/tools.py
Improve from_anovar #29 
Fix verbosity #36 
Add memory arg
> Improve from annovar

- howard/tools/from_annovar.py
- howard/tools/tools.py
- tests/test_tools_from_annovar.py
fix and improve and add multi_variant
> fix and improve and add multi_variant

- config/prioritization_profiles.json
- docs/howard.md
- howard/main.py
- howard/tools/annotation.py
- howard/tools/calculation.py
- howard/tools/databases.py
- howard/tools/prioritization.py
- howard/tools/process.py
- howard/tools/stats.py
- howard/tools/tools.py
- tests/test_tools_annotation.py
- tests/test_tools_calculation.py
- tests/test_tools_databases.py
- tests/test_tools_prioritization.py
- tests/test_tools_process.py
Fix nargs=+ option
Fix some args
Add help documentation
Add help in howard.md
> fix args nargs help #35 doc #4

- howard/commons.py
- howard/objects/variants.py
- tests/test_objects_database.py
- tests/test_objects_variants.py
Remove BCF format as input/output
Add TBL as TSV format
> remove BCF format as not processing with python

- howard/objects/database.py
- howard/objects/variants.py
- tests/data/annotations/nci60.json.gz.hdr
- tests/data/annotations/nci60.json.hdr
- tests/data/annotations/nci60.tsv.gz.hdr
- tests/data/annotations/nci60.tsv.hdr
- tests/data/annotations/nci60.vcf.gz.hdr
- tests/test_commons.py
- tests/test_objects_database.py
- tests/test_objects_variants.py
- tests/test_tools_annotation.py
- tests/test_tools_calculation.py
- tests/test_tools_convert.py
- tests/test_tools_prioritization.py
- tests/test_tools_process.py
- tests/test_tools_query.py
Refactor annotation parquet with Database object
Export Variant method use now Database export
Tests for all format of Database to annotate
> Refactor with database

- Dockerfile
Remove duckdb module pre-release
> clean duckdb installation

- howard/commons.py
- howard/objects/database.py
- setup.cfg
> fix duckdb extension loading

- .env
- docker-compose.yml
Network configuration of subnet and proxy
> network configuration #67

- howard/objects/hgvs.py
- howard/objects/transcript.py
- howard/objects/variants.py
- howard/tools/hgvs.py
- howard/tools/tools.py
- howard/utils.py
- setup.cfg
- tests/test_objects_hgvs.py
- tests/test_objects_variants.py
- tests/test_tools_hgvs.py
- tests/test_utils.py
HGVS annotation
tests
add version
> HGVS annotation #49 tests, add version

- howard/tools/databases.py
> fix #49 fix format refSeq to BED

- .gitignore
- README.md
- config/param.json
- docs/howard.md
- howard/commons.py
- howard/main.py
- howard/tools/databases.py
- howard/tools/tools.py
- tests/test_tools_databases.py
Fix logger: genompy interaction
Fix docs: change help and doc correct path (databases)
> fix #78 logger #4 docs

- howard/objects/variants.py
Improve regions database annotation
Improve InDel annotation
Improve update query for better performances
> fix #9 improve regions database annotation

- .env
- howard/commons.py
- howard/objects/database.py
- howard/objects/variants.py
- howard/tools/databases.py
- howard/tools/tools.py
- setup.cfg
- tests/test_objects_database.py
- tests/test_objects_variants.py
- tests/test_tools_databases.py
Fixes #3 #85 #86 improve annotation, fix input csv, improve dbNSFP download
> Fixes #3 #85 #86 improve annotation, fix input csv, improve dbNSFP

- .gitignore
- config/calculations_config.json
- howard/objects/variants.py
- howard/tools/calculation.py
- howard/tools/tools.py
- tests/data/operations_config_test.json
- tests/test_objects_variants.py
- tests/test_tools_calculation.py
Improve calculation tool
Add config file in JSON
Add options for SQL queries for calculation
> #10 improve calculation, add config file

- howard/objects/database.py
- howard/objects/variants.py
> fixes #96 improve export

- howard/commons.py
- howard/objects/database.py
- howard/objects/variants.py
- tests/test_objects_database.py
compressed file test (if exists or not)
compression type (bgzip, gzip,  none...)
pytest changes
> fixes #96 is compressed and compression type fixes

- howard/commons.py
- howard/main.py
- howard/objects/variants.py
- howard/tools/databases.py
- howard/tools/tools.py
- tests/test_tools_databases.py
Some fixes for threads management and dbSNP download
> Fixes threads management, dbSNP download

- howard/objects/database.py
> fix database export

- howard/tools/databases.py
Ass Parquet with exploded infos for dbSNP database
> Add explode infos to dSNP parquet generation #119

- howard/objects/variants.py
- howard/tools/stats.py
- howard/tools/tools.py
Add stats in json and markdown
> Add stats #127 output in markdown/json

- README.md
- config/config.json
- docs/help.html
- docs/help.md
- howard/main.py
- howard/tools/tools.py
Docs generation with help files in MarkDown and HTML format
> Add docs and help file generation #4

- howard/tools/databases.py
- tests/test_tools_databases.py
> Add refSeq in BED compressed #142

- howard/commons.py
add aria2c --async-dns option
check refseq bed columns format
> Add --async-dns option with aria2c

- howard/tools/from_annovar.py
- howard/tools/tools.py
- tests/test_from_annovar.py
> fix from_annovar #156

- howard/objects/variants.py
Fix includes a new error message to better identify that header is missing:
```
ValueError: Annotation failed: Annotation file '/tmp/avsnp150.parquet' header not found. Check for file '/tmp/avsnp150.parquet.hdr'
```
Fix also do not allow missing annotation file in quick annotation:
```
ValueError: Quick Annotation File /tmp/avsnp150.parquett does NOT exist
```
> Log messages fixes #266

- config/config.json
- howard/functions/commons.py
- howard/objects/variants.py
- tests/test_commons.py
- tests/test_variants_annotations_splice.py
- add docker configuration with automount, tmp and remove container option for tools launched with docker, could be global or tool specific
- update get bin command func
- split test for get bin command func
- clean annotation_splice, clean mount options, disable nextflow version check and add proxy env variable
- update testing for annotation_splice
> Update docker tools

- howard/functions/commons.py
- tests/test_commons.py
- tests/test_needed.py
- splice image from 0.2.1 to 0.2.2 (build splice env in nextflow pipeline)
- update get_bin_command and associated test (automount)
- fix get_bin_command_snpeff test, change path of snpeff binary
> Common func and associated test update

- .dockerignore
- howard/functions/databases.py
- howard/objects/variants.py
Fix explode infos fields
Fix hgmd folder for tests
Fix genome contigs' size variable (dict) for dbNSFP download
> Fix 0.12.0
